name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: pwd
      run: pwd
    - name: Restore dependencies
      run: dotnet restore 
      working-directory: ./
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  
  publish:
    
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: daanmath/foodoo_backend:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
